spring:
  application:
    name: Insurance Service
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:insurance_service}
    username: ${DB_USERNAME:insurance_app}
    password: ${DB_PASSWORD:insurance_app_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
management:
  endpoints:
    web:
      exposure:
        include: ${ACTUATOR_ENDPOINTS:health,info}
        
